### PR TITLE
FEATURE: Remove CLI dependency on generated project

### LINKED ISSUE #270: surround-cli does not need to be a dependency of the generated projects.
* Simplify  tasks `train` and `test`
* Remove `report_generator.py` from the generated projects

### PR DESCRIPTION
**Pull request by AkshatBajaj**
Depends on #272 
Fixes #270

### CODE REVIEW

**Comment by AkshatBajaj** [comment]
CI tests will fail until #272 gets merged

**Review by zacbrannelly — APPROVED** [review]
This worked for me once I fixed some issues with the experiment module (a Google Cloud dependency wasn't installing properly) but since the next PR remove's the experiment stuff, I think this PR is good to merge 👍

**Pull request merged**
