### PR TITLE
QUALITY: Add docker error message if there is no image built

### PR DESCRIPTION
**Pull request by Nikhii**
This PR is with regards to issue #155

### CODE REVIEW

**Comment by zacbrannelly** [comment]
This breaks the `surround run` tasks on Windows. Maybe use the `subprocess` module instead?

**Comment by zacbrannelly** [comment]
No docker image error message works, but when the image is built and you run `batch` the output isn't being printed to the terminal, don't know if its running correctly or not

**Comment by ucokzeko** [comment]
@Nikhii Can you please rebase this?
Thanks

**Comment by ScottyB** [comment]
Closing this PR as we don't want more subprocesses just for checking validity.

**Pull request closed without merging**
