### PR TITLE
FEATURE: Run & store experiments

### PR DESCRIPTION
**Pull request by zacbrannelly**
- [x] Implement `StorageDriver` and `FileStorageDriver` for pushing/pulling files from experimentation storage location (local for now)
- [x] Implement `ExperimentWriter` which can start & stop experiments, saving the required information to replicate the experiment plus keep track of metrics
- [x] Integrate `ExperimentWriter` with `surround run` via the `--experiment` flag
- [x] Support streaming logs in real-time to the experiment storage
- [x] Ensure configuration is setup before running an experiment
- [x] Save tree structure of input folder in experiments storage (and ignore input when creating zip)
- [x] Remove streaming metrics and instead use logging for this purpose
- [x] Take generating HTML out of experiment writer
- [x] Pass notes in before the experiment is ran via CLI
- [x] Make local experiment storage path convention based and default when no other specified e.g. `~/.experiments/local`
- [x] Make experiments default for `batch` and `train` tasks
- [x] Allow experiments to be ran in Docker containers (this will be supported when local storage locations are mounted to convention based paths, so we can just mount the container to those)
- [x] Fix formatting of logs
- [x] Write unit tests for `StorageDriver` & `FileStorageDriver`
- [x] Write unit tests for `ExperimentWriter`

Future work:
- Write documentation for these new classes
- Generate results report in `Visualiser` stage defined in generated projects (using tornado templates)
- Format logs as JSON, stream metrics this way
- Allow setting local experiment storage to SMB (shared drive) where drive mounting happens automatically and mounted to a convention based path e.g. `~/.experiments/shared_drive`
- Allow for setting an upstream (write to one storage location at a time)
- Discuss & Design how input should be handled

Examples:

Run an experiment
```
$ surround run train
$ surround run batch
$ surround run trainLocal
$ surround run batchLocal
```

Run a batch/train task without considering it an experiment
```
$ surround run trainLocal --no-experiment
```

Running without `surround run`:
```
$ python3 -m project_name --experiment --mode batch
```

Initialize config for first time
```
$ surround config
Enter your name (user.name): Zac Brannelly
Enter your email (user.email): zac.brannelly@email.com
```

Set configuration properties
```
$ surround config user.name Zac Brannelly
$ surround config user.email zac.bran@email.com 
```

Global config file:
```
user:
    name: Zac Brannelly
    email: zac.brannelly@email.com
experiment:
    url: ~/.experiments/local
    location:
        local: ~/.experiments/local
        shared: ~/.experiments/shared
```

```
writer = ExperimentWriter("~/.experiments")
writer.write_project("test_project", "Projects description here")
writer.start_experiment("test_project", "./test_project", args={"mode": "batch"}, notes=["first experiment"])
...
logging.info("This will be captured and streamed to experiment storage")
...
writer.end_experiment(metrics={"accuracy": 0.99})
```

To get the `results.html` you must render the HTML file and put it in the `output` folder of the project, with the name `results.html`

Experiment Storage Structure:
```
experimentation/
    project_name/
        project.json
        experiments/
            YYYY-MM-DDThh-mm-ss-mmmm/
                logs/
                    YYYY-MM-DDThh-mm-ss-mmmm_0.txt
                    ...
                    YYYY-MM-DDThh-mm-ss-mmmm_n.txt
                output/
                    ...
                code.zip
                execution_info.json
                results.json
                results.html
                log.txt
```

Relates to work designed in this doc: https://docs.google.com/document/d/1P2cSxUCCIx9xTerD4R_V2RKROOcGd-GMosPFVvqjHvI/edit?usp=sharing

Depends on #172, so will need to be rebased after it's merged

### CODE REVIEW

**Comment by ScottyB** [comment]
A couple of notes:
- By default the experiment flag should be set but only for train or batch modes
- A new generated project should have a default directory set to the project root directory. 
- We need to find a way to pass in a comment for the experiment before we run. This will also need to be disabled if we set experiment by default. 
- What is the `status.txt` file for?

**Comment by zacbrannelly** [comment]
@ScottyB `status.txt` is for communicating the state of the experiment, whether it is `RUNNING` or `COMPLETED`, could also later be extended to say whether the experiment succeeded or failed.

**Comment by zacbrannelly** [comment]
@ucokzeko `surround run batch` and `surround run train` won't work while this is a PR since they run the project in a Docker container, and this container uses the last release of Surround, which doesn't have the experimentation modules

**Comment by AkshatBajaj** [comment]
For testing purposes, we can manually copy the files in the directory and then instead of installing from pip we do `python3 setup.py install`.

**Comment by ucokzeko** [comment]
@zacbrannelly @AkshatBajaj My issue turned out to be that I had 2 versions of `surround` installed, so they were conflicted.
`trainLocal` and `batchLocal` work now after I fixed it.
I'll continue testing more stuff

**Comment by ucokzeko** [comment]
@zacbrannelly Couple questions:
1. Is there any instruction for pushing / pulling experiments?
2. Is there any instruction to mount experiment directory so that we can run it inside the docker?

**Comment by zacbrannelly** [comment]
This is an issue, but not due to this PR, for it to work you need to tell it to use the `WebRunner` using the `--runner` argument, e.g. `python3 -m project_name --experiment --mode train --runner WebRunner`

**Comment by ucokzeko** [comment]
I see
It's not actually a problem then
I was just using a wrong parameters combination
We just need to document this so that people know what to expect

**Pull request merged**
