### PR TITLE
TEST: Remove dependency on setup.py test as it is deprecated 

### LINKED ISSUE #250: Upgrade setup.py test as it is deprecated
https://github.com/pypa/setuptools/issues/1684
https://github.com/pytest-dev/pytest/issues/5534

### PR DESCRIPTION
**Pull request by AkshatBajaj**
Fixes #250 
https://github.com/pypa/setuptools/issues/1684

In order to test the surround library:
 - clone repo
 - `cd surround`
 - `tox`

In order to test the surround cli:
 - clone repo
 - `cd surround_cli`
 - `tox`

### CODE REVIEW

**Review by ScottyB — COMMENTED** [review]
How are test only requirements installed?

**Comment by AkshatBajaj** [comment]
It gets installed via `tox.ini` file
https://github.com/a2i2/surround/blob/3f1abf4c587653a789e4c930968cb866f2ba081d/surround/tox.ini

**Pull request merged**
