### PR TITLE
FEATURE: Split Data Tool

### PR DESCRIPTION
**Pull request by zacbrannelly**
From #137 

- [x] Make sure reset works for all flags
- [x] Modify script to work on a CSV file. In this case split the CSV file into multiple files under each folder.
- [x] Integrate the script into Surround command line tool
- [x] Properly document
- [x] Validate arguments, prevent errors
- [x] Add `--no-validate` flag so only test & train sets are created
- [x] Add `--no-shuffle` flag so we can disable shuffling
- [x] Make `--reset` argument take a path to a directory where the reset should happen
- [x] Remove initial visualize tool script from this branch
- [x] Remove pandas dependency

Example output:
```
$ surround split --help
usage: surround split [-h] (-t TEXT_FILE | -d DIRECTORY | -r RESET)
                      [-e EXTENSION] [-tr TRAIN] [-te TEST] [-va VALIDATE]
                      [-nv] [-ns] [-nh]

optional arguments:
  -h, --help            show this help message and exit
  -t TEXT_FILE, --text-file TEXT_FILE
                        Split CSV file into train/test/validate sets
  -d DIRECTORY, --directory DIRECTORY
                        Split directory into train/test/validate sets
  -r RESET, --reset RESET
                        Path to directory containing train/test/validate
                        folders to reset
  -e EXTENSION, --extension EXTENSION
                        File extension of the files to process (default: *)
  -tr TRAIN, --train TRAIN
                        Percentage of files for training (default: 80)
  -te TEST, --test TEST
                        Percentage of files for test (default: 10)
  -va VALIDATE, --validate VALIDATE
                        Percentage of files for validate (default: 10)
  -nv, --no-validate    Don't produce a validation set when splitting
  -ns, --no-shuffle     Don't randomise when splitting data
  -nh, --no-header      Use this flag when the CSV file has no headers
```

Example split directory & reset operation:
```
$ surround split -d example/dataset/
Train count: 20
Test count: 5
Validate count: 3

$ surround split --reset example/dataset/
File count: 28
```

Example split file & reset operation:
```
$ surround split -t example/dataset.csv
Train count: 300
Test count: 30
Validate count: 20

$ surround split --reset example/
Record count: 350
```

Example split directory structure:
```
examples/dataset/
├── train
│   ├── image01.png
│   └── image02...
├── test
│   ├── image300.png
│   └── image301...
├── validate
│   ├── image500.png
│   └── image501...
```

Example CSV split result:
```
examples/
├── train
│   └── dataset.csv
├── test
│   └── dataset.csv
├── validate
│   └── dataset.csv
```

### CODE REVIEW

**Comment by ScottyB** [comment]
I'm not sure how the reset works or how I specify files/folders to reset. I run split on a file and get three different folders, all good, then I want to run reset to change the split values and the tool requires either a single file or directory.

**Comment by zacbrannelly** [comment]
The way I did it was basically whatever command you used to split them originally, just add `--reset` on the end and it will put them back to normal. So if you used `surround split -f test.csv` to split them you would just use `surround split -f test.csv --reset` to undo the operation.

**Comment by ScottyB** [comment]
```➜  quickfuel-reports git:(pr/4) ✗ surround split -d ./data_june 
Invalid arguments, use --help for more information```
```
➜  quickfuel-reports git:(pr/4) ✗ surround split -r ./data_june 
Traceback (most recent call last):
  File "/usr/local/bin/surround", line 11, in <module>
    load_entry_point('surround==0.0.0', 'console_scripts', 'surround')()
  File "/usr/local/lib/python3.7/site-packages/surround-0.0.0-py3.7.egg/surround/cli.py", line 465, in main
    execute_cli()
  File "/usr/local/lib/python3.7/site-packages/surround-0.0.0-py3.7.egg/surround/cli.py", line 453, in execute_cli
    parse_tool_args(parsed_args, remote_parser, split_parser, tool)
  File "/usr/local/lib/python3.7/site-packages/surround-0.0.0-py3.7.egg/surround/cli.py", line 384, in parse_tool_args
    split_cli.execute_split_tool(split_parser, parsed_args)
  File "/usr/local/lib/python3.7/site-packages/surround-0.0.0-py3.7.egg/surround/split/cli.py", line 207, in execute_split_tool
    reset_file(args.reset, args.no_header)
  File "/usr/local/lib/python3.7/site-packages/surround-0.0.0-py3.7.egg/surround/split/cli.py", line 148, in reset_file
    undo_split_file(os.path.join(reset_path, file_name), no_header)
  File "/usr/local/lib/python3.7/site-packages/surround-0.0.0-py3.7.egg/surround/split/split_data.py", line 99, in undo_split_file
    with open(train_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/scottbarnett/projects/lead/quickfuel-reports/data_june/train/2019_6_26.csv'
```

**Comment by ScottyB** [comment]
I'm having trouble resetting the set up below:
```
➜  analysis git:(pr/4) ✗ tree data
data
├── exprt_transactions_liberty_kingaroy_1.tsv
├── test
│   └── exprt_transactions_liberty_kingaroy.tsv
├── train
│   └── exprt_transactions_liberty_kingaroy.tsv
└── validate
    └── exprt_transactions_liberty_kingaroy.tsv

3 directories, 4 files
➜  analysis git:(pr/4) ✗ surround split --reset ./data
Failed to reset, invalid directory!
➜  analysis git:(pr/4) ✗ 
```

I'm also noticing that the calculation for the number of validate and test sets is wrong:
```
➜  analysis git:(pr/4) ✗ surround split --help
usage: surround split [-h] (-t TEXT_FILE | -d DIRECTORY | -r RESET)
                      [-e EXTENSION] [-tr TRAIN] [-te TEST] [-va VALIDATE]
                      [-nv] [-ns] [-nh]

optional arguments:
  -h, --help            show this help message and exit
  -t TEXT_FILE, --text-file TEXT_FILE
                        Split CSV file into train/test/validate sets
  -d DIRECTORY, --directory DIRECTORY
                        Split directory into train/test/validate sets
  -r RESET, --reset RESET
                        Path to directory containing train/test/validate
                        folders to reset
  -e EXTENSION, --extension EXTENSION
                        File extension of the files to process (default: *)
  -tr TRAIN, --train TRAIN
                        Percentage of files for training (default: 80)
  -te TEST, --test TEST
                        Percentage of files for test (default: 10)
  -va VALIDATE, --validate VALIDATE
                        Percentage of files for validate (default: 10)
  -nv, --no-validate    Don't produce a validation set when splitting
  -ns, --no-shuffle     Don't randomise when splitting data
  -nh, --no-header      Use this flag when the CSV file has no headers
➜  analysis git:(pr/4) ✗ surround split -d data_june
Train count: 30
Test count: 3
Validate count: 5
➜  analysis git:(pr/4) ✗ surround split -r data_june
File count 38
```
The documentation indicates that 10% (currently missing the % symbol) of the records are used for both the validate and test sets which means they should be equal or off by 1. The example above shows off by 2 (3 and 5).

**Comment by zacbrannelly** [comment]
@ScottyB Group tool is in a new PR, split tool can be merged if you are happy with it 👍

**Pull request merged**
