### PR TITLE
CONFIG: Migration to Github Actions

### PR DESCRIPTION
**Pull request by ucokzeko**

### CODE REVIEW

**Comment by ucokzeko** [comment]
@zacbrannelly Manually disabled Codefresh and tested it against `test.pypi` before putting in the release condition. The part that hasn't been tested is the actual release workflows and their conditions.

**Review by zacbrannelly — COMMENTED** [review]
Looks good to me :) Just one thing, we should probably delete the `codefresh.yml` in this PR.

**Comment by ucokzeko** [comment]
Good point :+1:

**Review by zacbrannelly — APPROVED** [review]
🚀

**Pull request merged**
