### PR TITLE
FEATURE: Implement a standard approach for versioning a project [CON-548]

### PR DESCRIPTION
**Pull request by AkshatBajaj**

### CODE REVIEW

**Comment by ScottyB** [comment]
What is the status of this PR? The Version stuff looks like it has been added to #245.

**Comment by ucokzeko** [comment]
> What is the status of this PR? The Version stuff looks like it has been added to #245.

It's waiting for #245 to get in then I believe this PR can go in as well. Mostly it's just for adding a standard way of versioning a generated project.

**Review by ucokzeko — APPROVED** [review]
LGTM

**Pull request merged**
