### PR TITLE
ENHANCE: Use Google Cloud Storage for experimentation storage

### PR DESCRIPTION
**Pull request by zacbrannelly**
- [x] Implement `GCloudStorageDriver`
- [x] Detect `gs://test_bucket` as a URL that uses the `GCloudStorageDriver`
- [x] Dynamically load the experiment explorer page (to improve user experience when using cloud)
- [x] Optimize streaming logs when using cloud storage

To use this you must do the following:
- Create a project in the Google Cloud Platform Console
- Create a storage bucket 
- Create a Service Account, give it permissions to use storage buckets
- Download the JSON credentials file
- Put the credentials somewhere safe
- Create an environment variable `GOOGLE_APPLICATION_CREDENTIALS` with the value as the path to the JSON credentials file
- Run the command `surround config experiment.url gs://{bucket-name-here}/`
- Run `surround experimentation`

Depends on #187 & #199

### CODE REVIEW

**Comment by Nikhii** [comment]
Hi Zac,
When i try to check the version of surround before running through the gcloud-experimentation i get the following error:
```
10-148-250-178:surround nikhil$ surround -v
Traceback (most recent call last):
  File "/Users/nikhil/anaconda3/bin/surround", line 11, in <module>
    load_entry_point('surround==0.0.0', 'console_scripts', 'surround')()
  File "/Users/nikhil/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/nikhil/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2691, in load_entry_point
    return ep.load()
  File "/Users/nikhil/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2322, in load
    return self.resolve()
  File "/Users/nikhil/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2328, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/nikhil/anaconda3/lib/python3.6/site-packages/surround-0.0.0-py3.6.egg/surround/cli.py", line 15, in <module>
    from .experiment.web import cli as experiment_cli
  File "/Users/nikhil/anaconda3/lib/python3.6/site-packages/surround-0.0.0-py3.6.egg/surround/experiment/__init__.py", line 1, in <module>
    from .experiment_writer import ExperimentWriter
  File "/Users/nikhil/anaconda3/lib/python3.6/site-packages/surround-0.0.0-py3.6.egg/surround/experiment/experiment_writer.py", line 9, in <module>
    from .drivers import get_driver_type_from_url
  File "/Users/nikhil/anaconda3/lib/python3.6/site-packages/surround-0.0.0-py3.6.egg/surround/experiment/drivers.py", line 4, in <module>
    from .gcloud_storage_driver import GCloudStorageDriver
  File "/Users/nikhil/anaconda3/lib/python3.6/site-packages/surround-0.0.0-py3.6.egg/surround/experiment/gcloud_storage_driver.py", line 4, in <module>
    from google.cloud import storage
  File "/Users/nikhil/anaconda3/lib/python3.6/site-packages/google_cloud_storage-1.20.0-py3.6.egg/google/cloud/storage/__init__.py", line 38, in <module>
    from google.cloud.storage.batch import Batch
  File "/Users/nikhil/anaconda3/lib/python3.6/site-packages/google_cloud_storage-1.20.0-py3.6.egg/google/cloud/storage/batch.py", line 29, in <module>
    from google.cloud import _helpers
  File "/Users/nikhil/anaconda3/lib/python3.6/site-packages/google_cloud_core-1.0.3-py3.6.egg/google/cloud/_helpers.py", line 31, in <module>
    import google.auth
ModuleNotFoundError: No module named 'google.auth'
```

**Comment by Nikhii** [comment]
This PR is working now. 
Earlier, I had to explicitly specify ```protobuf and google-auth``` libraries.
But it seems to work fine now.

**Comment by DungLai** [comment]
Note for window user: Path to credential need to use `/` instead of `\`. For example: 
`export GOOGLE_APPLICATION_CREDENTIALS=C:/Users/abcvu/Desktop/trash/credentials.json`

**Comment by DungLai** [comment]
How to give it permissions to use storage buckets:

1. Select the menu
2. Select IAM & admin
3. Select ADD
4. In the `new members` field, type in the `client_email` as specified in the JSON credentials
5. In the `select a role` dropdown, select `Storage Object Admin`
6. Click `Save`

**Pull request merged**
